"""
Django settings for zhivaya_poyma project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-only')
#'django-insecure-#3!hn2y!6i7$$!iy0$-sdle#fx@@d9@bj^@y&d)p36x@rdo^25'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    'живаяпойма.рф',
    'www.живаяпойма.рф',
    'xn--80aaepkivoi3n.xn--p1ai',
    'www.xn--80aaepkivoi3n.xn--p1ai',
]

CSRF_TRUSTED_ORIGINS = [
    'https://живаяпойма.рф',
    'https://www.живаяпойма.рф',
    'https://xn--80aaepkivoi3n.xn--p1ai',
    'https://www.xn--80aaepkivoi3n.xn--p1ai',
]

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 86400

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "core",
    "news",
    "leads",

    "ckeditor",
    "ckeditor_uploader"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- строго сюда
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zhivaya_poyma.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'zhivaya_poyma.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR.parent.parent / "public_html" / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#MEDIA_ROOT = '/home/users/j/j93531404/domains/xn--80aaepkivoi3n.xn--p1ai/media/'
#MEDIA_ROOT = BASE_DIR / "media"

# Разрешаем WhiteNoise обрабатывать не только статику, но и медиа-файлы
WHITENOISE_AUTOREFRESH = True
WHITENOISE_USE_FINDERS = True

# Папка, куда будут сохраняться загруженные файлы
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_FORCE_JPEG_COMPRESSION = True
CKEDITOR_IMAGE_QUALITY = 80
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_THUMBNAIL_SIZE = (300, 300)

CKEDITOR_CONFIGS = {
    "default": {
        "width": "100%",
        "height": 420,
        "toolbarCanCollapse": False,
        "forcePasteAsPlainText": True,
        "removePlugins": "stylesheetparser",
        "filebrowserUploadUrl": "/ckeditor/upload/",
        "toolbar": [
            [
                "Format",
                "Bold", "Italic", "Underline", "Strike",
                "-",
                "NumberedList", "BulletedList",
                "-",
                "Outdent", "Indent",
                "-",
                "Blockquote", "HorizontalRule",
                "-",
                "Link", "Unlink",
                "-",
                "Image", "Table",
                "-",
                "Undo", "Redo",
                "-",
                "RemoveFormat", "Maximize", "Source",
            ],
        ],
    },
}
