# Generated by Django 6.0.6 on 2026-07-17 16:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, verbose_name='Вводный текст')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=220, verbose_name='Подзаголовок')),
                ('lead', models.TextField(blank=True, verbose_name='Лид')),
                ('body', wagtail.fields.StreamField([('heading_section', 3), ('paragraph', 4), ('image_with_caption', 8), ('observation', 13), ('progress_note', 18), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Надзаголовок', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Короткий текст', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('text', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote']}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор / источник', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('credit', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Наблюдение', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Дата / сезон', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Место', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('date_label', 11), ('place', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Этап', 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Что сделано', 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'label': 'Что наблюдаем', 'required': False}), 17: ('wagtail.blocks.TextBlock', (), {'label': 'Что дальше', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('stage', 14), ('done', 15), ('seen', 16), ('next_step', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 20: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('note', 6)]], {})}, verbose_name='Содержимое записи')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
