# Generated by Django 6.0.6 on 2026-08-17 15:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalpage',
            name='lead',
        ),
        migrations.AddField(
            model_name='journalpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='event_date',
            field=models.DateField(blank=True, help_text='Дата события или наблюдения. Если не заполнена, будет показана дата публикации.', null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading_section', 4), ('image_with_caption', 8), ('observation', 13), ('progress_note', 18), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Надзаголовок', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Короткий текст', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('eyebrow', 1), ('title', 2), ('text', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор / источник', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('credit', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Наблюдение', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Дата / сезон', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Место', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('date_label', 11), ('place', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Этап', 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Что сделано', 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'label': 'Что наблюдаем', 'required': False}), 17: ('wagtail.blocks.TextBlock', (), {'label': 'Что дальше', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('stage', 14), ('done', 15), ('seen', 16), ('next_step', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 20: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('note', 6)]], {})}, verbose_name='Содержимое записи'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=220, verbose_name='Краткое описание'),
        ),
    ]
