# Generated by Django 6.0.6 on 2026-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journalpage_lead_journalpage_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Краткое описание'),
        ),
    ]
