# Generated by Django 6.0.6 on 2026-09-01 20:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journalpage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='cover_caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подпись к обложке'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='cover_credit',
            field=models.CharField(blank=True, max_length=300, verbose_name='Автор / источник обложки'),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('heading_section', 4), ('image_with_caption', 8), ('observation', 13), ('progress_note', 18), ('cta', 21), ('external_video', 25), ('local_video', 30)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Надзаголовок', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Короткий текст', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('eyebrow', 1), ('title', 2), ('text', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Автор / источник', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('credit', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Наблюдение', 'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Дата / сезон', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Место', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('date_label', 11), ('place', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Этап', 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'label': 'Что сделано', 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'label': 'Что наблюдаем', 'required': False}), 17: ('wagtail.blocks.TextBlock', (), {'label': 'Что дальше', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('stage', 14), ('done', 15), ('seen', 16), ('next_step', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'required': True}), 20: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 19), ('url', 20), ('note', 6)]], {}), 22: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Вставьте ссылку на YouTube, VK Видео, RuTube или другой поддерживаемый сервис.', 'label': 'Ссылка на видео', 'max_height': 800, 'max_width': 1200, 'required': True}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'max_length': 500, 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Автор / источник', 'max_length': 300, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('video', 22), ('caption', 23), ('credit', 24)]], {}), 26: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Загрузите MP4 или WebM в раздел Documents Wagtail.', 'label': 'Видео файл', 'required': True}), 27: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Статичная картинка до запуска видео. Рекомендуется для длинных роликов.', 'label': 'Постер', 'required': False}), 28: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Запускать автоматически без звука', 'required': False}), 29: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Повторять видео', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('video', 26), ('poster', 27), ('caption', 23), ('credit', 24), ('autoplay', 28), ('loop', 29)]], {})}, verbose_name='Содержимое записи'),
        ),
    ]
