name: Deploy Open Floodplain Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Указываем GitHub запускать задачу именно на вашем домашнем сервере
    runs-on: self-hosted

    steps:
      - name: Deploy to Jino directly
        run: |
          # Настраиваем обычный SSH-ключ, так как мы уже под нужным IP
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Подключаемся напрямую к Jino без всяких прокси
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/users/j/***/domains/xn--80aaepkivoi3n.xn--p1ai/zhivaya-poyma/zhivaya_poyma/
            source /home/users/j/***/domains/xn--80aaepkivoi3n.xn--p1ai/.venv/python313/bin/activate
            git pull origin main
            
            python manage.py check
            python manage.py makemigrations --noinput
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            
            #touch zhivaya_poyma/wsgi.py
            touch ../../tmp/restart.txt
          EOF