name: Deploy Open Floodplain Project

on:
  push:
    branches:
      - main  # или master, в зависимости от вашей главной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Jino via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходим в папку с проектом
            cd /home/users/j/j93531404/domains/xn--80aaepkivoi3n.xn--p1ai/zhivaya-poyma/zhivaya_poyma
            
            # Активируем виртуальное окружение (подставьте свой путь)
            source /home/users/j/j93531404/domains/xn--80aaepkivoi3n.xn--p1ai/.venv/python313/bin/activate
            
            # Подтягиваем изменения
            git pull origin main
            
            # Устанавливаем новые зависимости, если они появились
            #pip install -r requirements.txt
            
            # Выполняем рутинные команды Django
            python manage.py check
            python manage.py makemigrations --noinput
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            
            # Перезапускаем веб-сервер (gunicorn, uwsgi или touch wsgi.py)
            # Например, для перезапуска Django на Jino Спектр часто достаточно:
            touch zhivaya_poyma/wsgi.py
